apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-app
  template:
    metadata:
      labels:
        app: greeting-app
    spec:
      containers:
      - name: greeting-app
        image: himanshu718/greeting-app:latest   # Use your Docker Hub username and image name
        ports:
        - containerPort: 5000
